### ISSUE TITLE
customize sub-p2p protocols for all network communications

### ISSUE THREAD

**Issue by 0xed1s0n** [verisense-network/vrs-cli#2]
We need a `NetworkProvider` to replace the mocking signal and do other tasks.

The `NetworkProvider` should register the subprotocol endpoints into existing p2p connections;
The `NetworkProvider` needs to impl `futures::Stream` trait to yield networking events then dispatch to upper layers. Thus the `Output` of this stream should not be concreate types.
The `NetworkProvider` will be instaniated in `cage.rs` then poll the next within `select!`

**Comment by miketang84** [comment]
Done
